# Generated by Django 5.1.2 on 2024-10-12 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('icon_url', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageable_id', models.IntegerField()),
                ('imageable_type', models.CharField(choices=[('user', 'User'), ('listing', 'Listing')], max_length=20)),
                ('image_url', models.TextField()),
                ('caption', models.TextField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=35, null=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('property_type', models.CharField(blank=True, choices=[('apartment', 'Apartment'), ('house', 'House'), ('guest_house', 'Guest House'), ('farmhouse', 'Farmhouse'), ('hostel', 'Hostel'), ('hotel', 'Hotel')], max_length=20, null=True)),
                ('room_type', models.CharField(blank=True, choices=[('entire_home', 'Entire Home/Apt'), ('private_room', 'Private Room'), ('shared_room', 'Shared Room')], max_length=20, null=True)),
                ('bedrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('beds', models.PositiveIntegerField(blank=True, null=True)),
                ('bathrooms', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('accommodates', models.PositiveIntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('price_per_night', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cleaning_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('minimum_nights', models.PositiveIntegerField(blank=True, null=True)),
                ('maximum_nights', models.PositiveIntegerField(blank=True, null=True)),
                ('cancellation_policy', models.CharField(blank=True, choices=[('flexible', 'Flexible'), ('moderate', 'Moderate'), ('strict', 'Strict')], max_length=20, null=True)),
                ('instant_bookable', models.BooleanField(default=False)),
                ('house_rules', models.TextField(blank=True)),
                ('listing_status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending_approval', 'Pending Approval'), ('suspended', 'Suspended')], max_length=20, null=True)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_in_start_time', models.TimeField(blank=True, null=True)),
                ('check_in_end_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('address_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adress_listing', to='myapp.address')),
                ('amenities', models.ManyToManyField(related_name='listings', to='myapp.amenity')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
