# Generated by Django 5.1.2 on 2024-10-18 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_image_imageable_id_image_listing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='amenities',
        ),
        migrations.CreateModel(
            name='ListingAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_highlighted', models.BooleanField(default=False)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.amenity')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.listing')),
            ],
            options={
                'verbose_name': 'Listing Amenity',
                'verbose_name_plural': 'Listing Amenities',
                'unique_together': {('listing', 'amenity')},
            },
        ),
    ]
