# Generated by Django 5.1.2 on 2024-10-18 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_property_types_alter_listing_property_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PROPERTY_TYPES',
            new_name='Propertype',
        ),
    ]
