# Generated by Django 5.1.2 on 2024-10-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_property_types_propertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='property_type',
            field=models.CharField(blank=True, choices=[('apartment', 'Apartment'), ('house', 'House'), ('guest_house', 'Guest House'), ('farmhouse', 'Farmhouse'), ('hostel', 'Hostel'), ('hotel', 'Hotel')], max_length=20, null=True),
        ),
    ]
